parameters:
    database_driver: pdo_pgsql
    database_host: null
    database_port: 5432
    database_name: ${DBNAME}
    database_user: ${DBUSER}
    database_password: ${DBPASS}
    database_path: null
    database_table_prefix: wallabag_
    database_socket: /tmp/.s.PGSQL.5432
    database_charset: utf8

    domain_name: ${FQDN}

    mailer_transport: smtp
    mailer_user: 
    mailer_password: 
    mailer_host: 
    mailer_port:
    mailer_encryption: 
    mailer_auth_mode:

    locale: ${LOCALE}

    # A secret key that's used to generate certain security-related tokens
    secret: ${SECRET}

    # two factor stuff
    twofactor_auth:
    twofactor_sender:

    # fosuser stuff
    fosuser_registration: false
    fosuser_confirmation: false

    # how long the access token should live in seconds for the API
    fos_oauth_server_access_token_lifetime: 3600
    # how long the refresh token should life in seconds for the API
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: no_user@noreply.com

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: 
    redis_host: 
    redis_port: 
    redis_path: 
    redis_password: 

    # sentry logging
    sentry_dsn: null

    # User-friendly name of your instance for 2FA issuer
    server_name:
